# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "Client1" do |c1|
    c1.vm.hostname = "Client1"
    c1.vm.provider "virtualbox" do |v|
      v.name = "Client1"
      v.memory = 256
    end
    c1.vm.network "private_network", ip: "10.0.1.2", virtualbox__intnet: "netcl1", :netmask => "255.255.255.0"
    c1.vm.provision "shell", run: "once", path: "Client1.sh"
  end

  config.vm.define "Client2" do |c2|
    c2.vm.hostname = "Client2"
    c2.vm.provider "virtualbox" do |v|
      v.name = "Client1"
      v.memory = 256
    end
    c2.vm.network "private_network", ip: "10.0.2.2", virtualbox__intnet: "netcl2", :netmask => "255.255.255.0"
    c2.vm.provision "shell", run: "once", path: "Client2.sh"
  end

  config.vm.define "ClientRouter" do |cr|
    cr.vm.hostname = "ClientRouter"
    cr.vm.provider "virtualbox" do |v|
      v.name = "ClientRouter"
      v.memory = 256
    end
    
    cr.vm.network "private_network", bridge: "eth1", ip: "192.168.1.3", virtualbox__intnet: "extnet", :netmask => "255.255.255.0"
    cr.vm.network "private_network", bridge: "eth2", ip: "10.0.1.1", virtualbox__intnet: "netcl1", :netmask => "255.255.255.0"
    cr.vm.network "private_network", bridge: "eth3", ip: "10.0.2.1", virtualbox__intnet: "netcl2", :netmask => "255.255.255.0"
    cr.vm.provision "shell", run: "once", path: "ClientRouter.sh"
  end

  config.vm.define "MasterRouter" do |mr|
    mr.vm.hostname = "MasterRouter"
    mr.vm.provider "virtualbox" do |v|
      v.name = "MasterRouter"
      v.memory = 256
    end
    mr.vm.network "private_network", ip: "192.168.1.1", virtualbox__intnet: "extnet", :netmask => "255.255.255.0"
    mr.vm.network "private_network", ip: "10.0.0.1", virtualbox__intnet: "intnet", :netmask => "255.255.255.0"
    mr.vm.provision "shell", run: "once", path: "MasterRouter.sh"
  end

  # config.vm.define "SlaveRouter" do |sr|
  #   sr.vm.hostname = "SlaveRouter"iptables -t filter -L FORWARD -n
  #   sr.vm.provider "virtualbox" do |v|
  #     v.name = "SlaveRouter"
  #     v.memory = 512
  #   end
  #   sr.vm.network "private_network", ip: "192.168.1.2/24", virtualbox__intnet: true
  #   sr.vm.network "private_network", ip: "10.0.0.2/24", virtualbox__intnet: true
  # end

  config.vm.define "Server1" do |s1|
    s1.vm.hostname = "Server1"
    s1.vm.provider "virtualbox" do |v|
      v.name = "Server1"
      v.memory = 256
    end
    s1.vm.network "private_network", ip: "10.0.0.101", virtualbox__intnet: "intnet", :netmask => "255.255.255.0"
    s1.vm.network "private_network", ip: "172.16.0.11", virtualbox__intnet: "clusternet", :netmask => "255.255.255.0"
    s1.vm.provision "shell", run: "once", path: "ServersScript/installHttpd.sh", args: "10.0.0.101"
    # s1.vm.provision "shell", run: "once", path: "Server1.sh"
  end

  # config.vm.define "Server2" do |s2|
  #   s2.vm.hostname = "Server2"
  #   s2.vm.provider "virtualbox" do |v|
  #     v.name = "Server2"
  #     v.memory = 256
  #   end
  #   s2.vm.network "private_network", ip: "10.0.0.102", virtualbox__intnet: "intnet", :netmask => "255.255.255.0"
  #   s2.vm.network "private_network", ip: "172.16.0.12", virtualbox__intnet: "clusternet", :netmask => "255.255.255.0"
  #   s2.vm.provision "shell", run: "once", path: "Server2.sh"
  # end

  # config.vm.define "Server3" do |s3|
  #   s3.vm.hostname = "Server3"
  #   s3.vm.provider "virtualbox" do |v|
  #     v.name = "Server3"
  #     v.memory = 256
  #   end
  #   s3.vm.network "private_network", ip: "10.0.0.102", virtualbox__intnet: "intnet", :netmask => "255.255.255.0"
  #   s3.vm.network "private_network", ip: "172.16.0.13", virtualbox__intnet: "clusternet", :netmask => "255.255.255.0"
  #   s3.vm.provision "shell", run: "once", path: "Server3.sh"
  # end
end